import styles from '@/styles/components/MentorThanks.module.scss'

const volunteers = [
  'Advait',
  'Akira',
  'Alex Beloiu ',
  'Amy',
  'Angela Yuan',
  'April',
  'Blaire',
  'Brian',
  'Cole Morehouse',
  'Cooper Saye',
  'Daniel Malis',
  'Daphne Tsai',
  'Deric Dinu Daniel',
  'Desola Fujah',
  'Dev Kunjadia',
  'Emily Ma',
  'Harry Sanders',
  'Joshua Sum',
  'Kevin Wang',
  'Meghan Joshi',
  'Mihir S. Arya',
  'Navya Kumar',
  'Phoebe Oh',
  'Pranay Gupta',
  'Raghav',
  'Renee',
  'Shirvil Sheth',
  'Shrey Pandya',
  'Sohavni Singh',
  'Spencer Goodwin',
  'Tyrus',
  'Vijaya ',
  'Zain Zai',
  'Derek Miller',
  'Akshay Kannan',
  'Ashwin Kumar',
  'Daniel Malis',
  'Dheera (mentor)',
  'Lucas',
  'Madhav Sharma',
  'Rohan Nagavardhan',
  'Vishnu',
  'Hillary Luan',
  'Jiayao Su',
  'Sachin Rammoorthy',
  'Muhan Zhao',
  'Emerson Ramey',
  'Yun Lee',
  'Lisa Guo',
  'Namrata Arora',
  'Ping Yu',
  'Anees Shaikh',
  'Andrew Myrick',
  'Connor Riley',
  'Jack Wu',
  'Anusha Bohra',
  'Yutong Xu',
  'Zihao Deng',
  'Srinath Sridhar',
  'Mitchell Bloch',
  'Mohnish Aggarwal',
  'Kiran Menon',
  'Saad Movania',
  'Angelina Ilijevski',
  'Ashish Mahuli',
  'Augustine Osagie',
  'Jinyi Wu',
  'Christopher Lee',
  'Raghav Prabhu',
  'Drishti Srivastava',
  'Abinav Sadhneni',
  'Mukundh',
  'Swaraj',
  'Layne',
  'Arjun Lalwani', // start of judges
  'Camden Pastyrnak ',
  'Peter Wu',
  'Adviti Mishra',
  'Ethan Holmes',
  'Samay Shamdasani',
  'Advait Iyer',
  'eliam medina',
  'Robert Dick',
  'Dani Grant',
  'Divya Vemuri',
  'Krishna Chaitanya Rao Kathala',
  'Shashank Palakurthi',
  'Shivendra Srivastava',
  'Saloni Thakkar',
  'Mukundh Murthy',
]

export default function MentorThanks() {
  return (
    <div className={styles.container}>
      <h2>Thank You to our Volunteers!</h2>
      <div className={styles.nameContainer}>
        {volunteers.map((name) => (
          <p key={name}>{name}</p>
        ))}
      </div>
    </div>
  )
}
